/**
 *     Copyright (C) 2013-2014  the original author or authors.
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License,
 *     any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>
 */
package org.excalibur.fm.configuration.ui;

import java.awt.event.ItemEvent;
import org.excalibur.fm.solver.constraints.Variable;
import org.excalibur.fm.solver.constraints.Vars;

public class ObjectivePopup extends javax.swing.JFrame
{
    /**
     * Serial code version <code>serialVersionUID</code> for serialization. 
     */
    private static final long serialVersionUID = 3219690204520327457L;
    private Variable selectedVar_;

    /**
     * Creates new form ObjectivesDefinitionForm
     */
    public ObjectivePopup()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgObjectives = new javax.swing.ButtonGroup();
        plnVariables = new javax.swing.JPanel();
        rbCpu = new javax.swing.JRadioButton();
        rbCost = new javax.swing.JRadioButton();
        rbMemory = new javax.swing.JRadioButton();

        setAlwaysOnTop(true);
//        setType(java.awt.Window.Type.POPUP);

        plnVariables.setBorder(javax.swing.BorderFactory.createTitledBorder("Which variable can be desconsidered?"));

        bgObjectives.add(rbCpu);
        rbCpu.setText("vCPU");
        rbCpu.setName(""); // NOI18N
        rbCpu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbCostItemStateChanged(evt);
            }
        });

        bgObjectives.add(rbCost);
        rbCost.setText("Cost");
        rbCost.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbCostItemStateChanged(evt);
            }
        });

        bgObjectives.add(rbMemory);
        rbMemory.setText("Memory");
        rbMemory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbCostItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout plnVariablesLayout = new javax.swing.GroupLayout(plnVariables);
        plnVariables.setLayout(plnVariablesLayout);
        plnVariablesLayout.setHorizontalGroup(
            plnVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnVariablesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbCpu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbCost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbMemory)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        plnVariablesLayout.setVerticalGroup(
            plnVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbCpu)
                .addComponent(rbCost)
                .addComponent(rbMemory))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plnVariables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plnVariables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(338, 102));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbCostItemStateChanged(java.awt.event.ItemEvent evt)
    {// GEN-FIRST:event_rbCostItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            if (this.rbCost.equals(evt.getSource()))
            {
                selectedVar_ = Variable.valueOf(Vars.COST.name());
            }
            else if (this.rbCpu.equals(evt.getSource()))
            {
                selectedVar_ = Variable.valueOf(Vars.CORES.name());
            }
            else
            {
                selectedVar_ = Variable.valueOf(Vars.MEMORY.name());
            }

            this.dispose();
        }
    }// GEN-LAST:event_rbCostItemStateChanged

    protected Variable getSelectedVar()
    {
        return this.selectedVar_;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgObjectives;
    private javax.swing.JPanel plnVariables;
    private javax.swing.JRadioButton rbCost;
    private javax.swing.JRadioButton rbCpu;
    private javax.swing.JRadioButton rbMemory;
    // End of variables declaration//GEN-END:variables
}
